require("dotenv").config({ path: "../.env" });
const mongoose = require("mongoose");
const Product = require("../models/productModel");

const productNames = [
  "Warning Shirt",
  "Floral Shirt",
  "Blacked Out Shirt",
  "Japanese Original",
  "Breather Original",
  "Unique Top",
  "Slay Outfit",
  "Party Night Outfit",
  "Green Lines",
  "Black n' White",
  "Sapped Brown",
  "Casual Party Wear",
  "The Goofy One",
  "Kaki Gen-Z Version",
  "Pysched Shirt",
  "The Many-Faced God",
  "Green Lines",
  "Black n' White",
  "Sapped Brown",
  "Casual Party Wear",
  "The Goofy One",
  "Kaki Gen-Z Version",
  "Pysched Shirt",
  "The Many-Faced God",
  "Green Casuals",
  "Blue Casuals",
  "Women's Joggers",
  "Casual Pants",
  "Crop Top",
  "Professional Pants",
  "Sky Casuals",
  "Party Night Pants",
];

const productDescriptions = [
  {
    material_composition: "100% Polyester",
    pattern: "Striped",
    fit_type: "Regular Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Button-Down",
    length: "Short Length",
    country_of_origin: "China",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Premium Polyester fabric for a comfortable feel",
      "Casual Striped Shirt for men",
      "Regular Fit (Please check size chart for measurements)",
      "Suitable for everyday wear",
      "Size chart - S-36, M-38, L-40, XL-42, XXL-44",
    ],
    additional_information: {
      manufacturer: "XYZ Clothing Co., 123 Industrial Park, Beijing, China",
      packer: "XYZ Clothing Co., 123 Industrial Park, Beijing, China",
      item_weight: "520 g",
      item_dimensions: "22 x 18 x 3.8 Centimeters",
    },
  },
  {
    material_composition: "95% Cotton, 5% Spandex",
    pattern: "Printed",
    fit_type: "Slim Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "V-Neck",
    length: "Long Length",
    country_of_origin: "Bangladesh",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and stretchy Cotton blend fabric",
      "Trendy Printed Top for women",
      "Slim Fit for a flattering look",
      "Perfect for casual outings",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "ABC Fashion Ltd., 456 Textile Avenue, Dhaka, Bangladesh",
      packer: "ABC Fashion Ltd., 456 Textile Avenue, Dhaka, Bangladesh",
      item_weight: "470 g",
      item_dimensions: "24 x 19 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "80% Cotton, 20% Polyester",
    pattern: "Solid",
    fit_type: "Regular Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Classic",
    length: "Standard Length",
    country_of_origin: "Vietnam",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and breathable Cotton blend fabric",
      "Classic Solid Shirt for men",
      "Regular Fit suitable for most body types",
      "Versatile for various occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Fashion House Ltd., Ho Chi Minh City, Vietnam",
      packer: "Fashion House Ltd., Ho Chi Minh City, Vietnam",
      item_weight: "480 g",
      item_dimensions: "23 x 21 x 4 Centimeters",
    },
  },
  {
    material_composition: "100% Linen",
    pattern: "Checkered",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Spread Collar",
    length: "Long Length",
    country_of_origin: "Italy",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable and lightweight Linen fabric",
      "Casual Checkered Shirt for men",
      "Slim Fit for a modern look",
      "Ideal for summer outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Italian Fashion House, Milan, Italy",
      packer: "Italian Fashion House, Milan, Italy",
      item_weight: "490 g",
      item_dimensions: "26 x 22 x 4.2 Centimeters",
    },
  },
  {
    material_composition: "70% Cotton, 30% Polyester",
    pattern: "Solid",
    fit_type: "Regular Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Button-Down",
    length: "Short Length",
    country_of_origin: "Spain",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Comfortable and durable Cotton-Polyester blend",
      "Classic Solid Shirt for men",
      "Regular Fit for everyday wear",
      "Suitable for both casual and formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Fashion House S.L., Madrid, Spain",
      packer: "Fashion House S.L., Madrid, Spain",
      item_weight: "530 g",
      item_dimensions: "28 x 23 x 4.5 Centimeters",
    },
  },
  {
    material_composition: "100% Cotton",
    pattern: "Solid",
    fit_type: "Regular Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "V-Neck",
    length: "Standard Length",
    country_of_origin: "India",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and breathable Cotton fabric",
      "Classic Solid T-shirt for men",
      "Regular Fit for comfortable wear",
      "Suitable for casual occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Fashion House Pvt. Ltd., Mumbai, India",
      packer: "Fashion House Pvt. Ltd., Mumbai, India",
      item_weight: "480 g",
      item_dimensions: "24 x 20 x 4.2 Centimeters",
    },
  },
  {
    material_composition: "95% Polyester, 5% Spandex",
    pattern: "Floral",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Round Neck",
    length: "Standard Length",
    country_of_origin: "Vietnam",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Stretchy Polyester-Spandex blend fabric",
      "Stylish Floral Print T-shirt for men",
      "Slim Fit for a modern look",
      "Perfect for summer styling",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Style Creations Ltd., Ho Chi Minh City, Vietnam",
      packer: "Style Creations Ltd., Ho Chi Minh City, Vietnam",
      item_weight: "450 g",
      item_dimensions: "22 x 18 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "100% Cotton",
    pattern: "Striped",
    fit_type: "Regular Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Button-Down",
    length: "Long Length",
    country_of_origin: "Bangladesh",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Premium Cotton fabric for a comfortable feel",
      "Classic Striped Shirt for men",
      "Regular Fit suitable for most body types",
      "Ideal for formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Classic Shirts Ltd., Dhaka, Bangladesh",
      packer: "Classic Shirts Ltd., Dhaka, Bangladesh",
      item_weight: "520 g",
      item_dimensions: "26 x 22 x 4 Centimeters",
    },
  },
  {
    material_composition: "80% Cotton, 20% Polyester",
    pattern: "Checkered",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Spread Collar",
    length: "Short Length",
    country_of_origin: "Italy",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable Cotton-Polyester blend fabric",
      "Trendy Checkered Shirt for men",
      "Slim Fit for a stylish look",
      "Perfect for casual outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Italian Style Creations, Milan, Italy",
      packer: "Italian Style Creations, Milan, Italy",
      item_weight: "490 g",
      item_dimensions: "28 x 23 x 4.5 Centimeters",
    },
  },
  {
    material_composition: "100% Linen",
    pattern: "Solid",
    fit_type: "Relaxed Fit",
    sleeve_type: "3/4 Sleeve",
    collar_style: "V-Neck",
    length: "Long Length",
    country_of_origin: "Spain",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and breathable Linen fabric",
      "Relaxed Fit Solid Top for women",
      "3/4 Sleeve design for a casual vibe",
      "Great for everyday wear",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Linen Fashion House S.L., Madrid, Spain",
      packer: "Linen Fashion House S.L., Madrid, Spain",
      item_weight: "460 g",
      item_dimensions: "25 x 20 x 4 Centimeters",
    },
  },
  {
    material_composition: "100% Cotton",
    pattern: "Floral",
    fit_type: "Regular Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Button-Down",
    length: "Short Length",
    country_of_origin: "India",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and breathable Cotton fabric",
      "Elegant Floral Shirt for men",
      "Regular Fit for comfortable wear",
      "Ideal for casual outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Elegant Creations Pvt. Ltd., Mumbai, India",
      packer: "Elegant Creations Pvt. Ltd., Mumbai, India",
      item_weight: "490 g",
      item_dimensions: "26 x 21 x 4 Centimeters",
    },
  },
  {
    material_composition: "90% Cotton, 10% Polyester",
    pattern: "Checkered",
    fit_type: "Slim Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Spread Collar",
    length: "Long Length",
    country_of_origin: "Bangladesh",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and durable Cotton-Polyester blend fabric",
      "Classic Checkered Shirt for men",
      "Slim Fit for a modern look",
      "Suitable for both casual and formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Checkered Shirts Ltd., Dhaka, Bangladesh",
      packer: "Checkered Shirts Ltd., Dhaka, Bangladesh",
      item_weight: "510 g",
      item_dimensions: "27 x 22 x 4.2 Centimeters",
    },
  },
  {
    material_composition: "100% Linen",
    pattern: "Solid",
    fit_type: "Relaxed Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "V-Neck",
    length: "Short Length",
    country_of_origin: "Italy",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable and lightweight Linen fabric",
      "Relaxed Fit Solid Top for women",
      "Short Sleeve design for a casual vibe",
      "Perfect for summer styling",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Linen Fashion House, Milan, Italy",
      packer: "Linen Fashion House, Milan, Italy",
      item_weight: "470 g",
      item_dimensions: "25 x 20 x 4 Centimeters",
    },
  },
  {
    material_composition: "80% Cotton, 20% Polyester",
    pattern: "Striped",
    fit_type: "Regular Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Classic",
    length: "Standard Length",
    country_of_origin: "Vietnam",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Comfortable Cotton-Polyester blend fabric",
      "Classic Striped Shirt for men",
      "Regular Fit suitable for most body types",
      "Versatile for various occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Striped Shirts Ltd., Ho Chi Minh City, Vietnam",
      packer: "Striped Shirts Ltd., Ho Chi Minh City, Vietnam",
      item_weight: "500 g",
      item_dimensions: "28 x 23 x 4.5 Centimeters",
    },
  },
  {
    material_composition: "95% Polyester, 5% Spandex",
    pattern: "Printed",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Mandarin Collar",
    length: "Short Length",
    country_of_origin: "China",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Stretchy Polyester-Spandex blend fabric",
      "Stylish Printed Shirt for men",
      "Slim Fit for a modern look",
      "Perfect for casual occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Printed Shirts Co., Shanghai, China",
      packer: "Printed Shirts Co., Shanghai, China",
      item_weight: "480 g",
      item_dimensions: "24 x 19 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "60% Cotton, 40% Polyester",
    pattern: "Tie-Dye",
    fit_type: "Relaxed Fit",
    sleeve_type: "Sleeveless",
    collar_style: "Scoop Neck",
    length: "Crop Length",
    country_of_origin: "USA",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and lightweight Cotton-Polyester blend fabric",
      "Trendy Tie-Dye Tank Top for women",
      "Relaxed Fit for casual comfort",
      "Perfect for summer festivals",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Tie-Dye Creations Inc., Los Angeles, USA",
      packer: "Tie-Dye Creations Inc., Los Angeles, USA",
      item_weight: "420 g",
      item_dimensions: "20 x 15 x 3 Centimeters",
    },
  },
  {
    material_composition: "70% Cotton, 30% Linen",
    pattern: "Striped",
    fit_type: "Relaxed Fit",
    sleeve_type: "3/4 Sleeve",
    collar_style: "Boat Neck",
    length: "Long Length",
    country_of_origin: "France",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable Cotton-Linen blend fabric",
      "Casual Striped Top for women",
      "Relaxed Fit for easy movement",
      "Ideal for beach vacations",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Striped Tops Co., Paris, France",
      packer: "Striped Tops Co., Paris, France",
      item_weight: "450 g",
      item_dimensions: "22 x 18 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "100% Silk",
    pattern: "Geometric",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Mock Neck",
    length: "Short Length",
    country_of_origin: "Italy",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Luxurious Silk fabric with a smooth finish",
      "Sophisticated Geometric Print Blouse for women",
      "Slim Fit for a flattering silhouette",
      "Perfect for evening gatherings",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Silk Elegance Ltd., Milan, Italy",
      packer: "Silk Elegance Ltd., Milan, Italy",
      item_weight: "380 g",
      item_dimensions: "18 x 15 x 2.5 Centimeters",
    },
  },
  {
    material_composition: "50% Linen, 50% Rayon",
    pattern: "Embroidered",
    fit_type: "Relaxed Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Peter Pan Collar",
    length: "Long Length",
    country_of_origin: "India",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable Linen-Rayon blend fabric",
      "Vintage-Inspired Embroidered Dress for women",
      "Relaxed Fit for bohemian chic style",
      "Ideal for outdoor garden parties",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Bohemian Dresses Co., Jaipur, India",
      packer: "Bohemian Dresses Co., Jaipur, India",
      item_weight: "520 g",
      item_dimensions: "26 x 22 x 4 Centimeters",
    },
  },
  {
    material_composition: "100% Organic Cotton",
    pattern: "Abstract",
    fit_type: "Relaxed Fit",
    sleeve_type: "Sleeveless",
    collar_style: "Halter Neck",
    length: "Maxi Length",
    country_of_origin: "Brazil",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and eco-friendly Organic Cotton fabric",
      "Artistic Abstract Print Maxi Dress for women",
      "Relaxed Fit for effortless style",
      "Perfect for summer beach vacations",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Organic Dresses Brazil, Sao Paulo, Brazil",
      packer: "Organic Dresses Brazil, Sao Paulo, Brazil",
      item_weight: "480 g",
      item_dimensions: "24 x 20 x 4.2 Centimeters",
    },
  },
  {
    material_composition: "80% Polyester, 20% Cotton",
    pattern: "Abstract",
    fit_type: "Slim Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Mandarin Collar",
    length: "Standard Length",
    country_of_origin: "South Korea",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Smooth and durable Polyester-Cotton blend fabric",
      "Modern Abstract Print Shirt for men",
      "Slim Fit for a sleek appearance",
      "Ideal for formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Fashion House Korea, Seoul, South Korea",
      packer: "Fashion House Korea, Seoul, South Korea",
      item_weight: "520 g",
      item_dimensions: "26 x 22 x 4 Centimeters",
    },
  },
  {
    material_composition: "100% Organic Cotton",
    pattern: "Animal Print",
    fit_type: "Relaxed Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Crew Neck",
    length: "Short Length",
    country_of_origin: "Kenya",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and eco-friendly Organic Cotton fabric",
      "Trendy Animal Print T-shirt for women",
      "Relaxed Fit for casual comfort",
      "Great for weekend outings",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Eco-Friendly Apparel Ltd., Nairobi, Kenya",
      packer: "Eco-Friendly Apparel Ltd., Nairobi, Kenya",
      item_weight: "450 g",
      item_dimensions: "22 x 18 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "70% Cotton, 30% Linen",
    pattern: "Tropical",
    fit_type: "Regular Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "V-Neck",
    length: "Short Length",
    country_of_origin: "Indonesia",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable Cotton-Linen blend fabric",
      "Vibrant Tropical Print Top for women",
      "Regular Fit for everyday wear",
      "Perfect for summer vacations",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Tropical Fashion Inc., Bali, Indonesia",
      packer: "Tropical Fashion Inc., Bali, Indonesia",
      item_weight: "480 g",
      item_dimensions: "24 x 20 x 4 Centimeters",
    },
  },
  {
    material_composition: "60% Cotton, 40% Polyester",
    pattern: "Polka Dot",
    fit_type: "Slim Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Button-Down",
    length: "Long Length",
    country_of_origin: "Brazil",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and durable Cotton-Polyester blend fabric",
      "Classic Polka Dot Shirt for men",
      "Slim Fit for a modern look",
      "Suitable for both casual and formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Polka Dot Apparel Ltd., Rio de Janeiro, Brazil",
      packer: "Polka Dot Apparel Ltd., Rio de Janeiro, Brazil",
      item_weight: "500 g",
      item_dimensions: "28 x 23 x 4.5 Centimeters",
    },
  },
  {
    material_composition: "90% Polyester, 10% Spandex",
    pattern: "Camouflage",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Crew Neck",
    length: "Standard Length",
    country_of_origin: "Vietnam",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Stretchy Polyester-Spandex blend fabric",
      "Stylish Camouflage Print T-shirt for men",
      "Slim Fit for a modern look",
      "Perfect for outdoor adventures",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Camouflage Apparel Co., Ho Chi Minh City, Vietnam",
      packer: "Camouflage Apparel Co., Ho Chi Minh City, Vietnam",
      item_weight: "470 g",
      item_dimensions: "25 x 20 x 4 Centimeters",
    },
  },
  {
    material_composition: "95% Cotton, 5% Spandex",
    pattern: "Striped",
    fit_type: "Regular Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Button-Down",
    length: "Long Length",
    country_of_origin: "Italy",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and stretchy Cotton-Spandex blend fabric",
      "Classic Striped Shirt for men",
      "Regular Fit suitable for most body types",
      "Versatile for various occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Striped Shirts Ltd., Milan, Italy",
      packer: "Striped Shirts Ltd., Milan, Italy",
      item_weight: "500 g",
      item_dimensions: "28 x 23 x 4.5 Centimeters",
    },
  },
  {
    material_composition: "85% Polyester, 15% Cotton",
    pattern: "Floral",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Spread Collar",
    length: "Standard Length",
    country_of_origin: "Thailand",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Smooth Polyester-Cotton blend fabric",
      "Stylish Floral Print Shirt for men",
      "Slim Fit for a modern silhouette",
      "Ideal for casual outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Floral Fashion Co., Bangkok, Thailand",
      packer: "Floral Fashion Co., Bangkok, Thailand",
      item_weight: "480 g",
      item_dimensions: "26 x 22 x 4 Centimeters",
    },
  },
  {
    material_composition: "70% Cotton, 30% Polyester",
    pattern: "Abstract",
    fit_type: "Relaxed Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "V-Neck",
    length: "Short Length",
    country_of_origin: "Spain",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Breathable Cotton-Polyester blend fabric",
      "Artistic Abstract Print Top for women",
      "Relaxed Fit for casual comfort",
      "Great for summer days",
      "Size chart - XS-32, S-34, M-36, L-38, XL-40",
    ],
    additional_information: {
      manufacturer: "Abstract Apparel Ltd., Barcelona, Spain",
      packer: "Abstract Apparel Ltd., Barcelona, Spain",
      item_weight: "450 g",
      item_dimensions: "22 x 18 x 3.5 Centimeters",
    },
  },
  {
    material_composition: "100% Linen",
    pattern: "Solid",
    fit_type: "Slim Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Classic",
    length: "Standard Length",
    country_of_origin: "Portugal",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Premium Linen fabric for a luxurious feel",
      "Classic Solid Shirt for men",
      "Slim Fit for a modern look",
      "Perfect for formal occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Linen Elegance Co., Lisbon, Portugal",
      packer: "Linen Elegance Co., Lisbon, Portugal",
      item_weight: "520 g",
      item_dimensions: "26 x 22 x 4 Centimeters",
    },
  },
  {
    material_composition: "90% Polyester, 10% Spandex",
    pattern: "Geometric",
    fit_type: "Slim Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Mandarin Collar",
    length: "Short Length",
    country_of_origin: "China",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Stretchy Polyester-Spandex blend fabric",
      "Stylish Geometric Print Shirt for men",
      "Slim Fit for a sleek appearance",
      "Ideal for casual outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Geometric Designs Inc., Shanghai, China",
      packer: "Geometric Designs Inc., Shanghai, China",
      item_weight: "470 g",
      item_dimensions: "25 x 20 x 4 Centimeters",
    },
  },
  {
    material_composition: "75% Cotton, 25% Linen",
    pattern: "Plaid",
    fit_type: "Regular Fit",
    sleeve_type: "Long Sleeve",
    collar_style: "Button-Down",
    length: "Long Length",
    country_of_origin: "Scotland",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Durable Cotton-Linen blend fabric",
      "Classic Plaid Shirt for men",
      "Regular Fit suitable for everyday wear",
      "Versatile for various occasions",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Plaid Fashion Co., Edinburgh, Scotland",
      packer: "Plaid Fashion Co., Edinburgh, Scotland",
      item_weight: "510 g",
      item_dimensions: "27 x 22 x 4.2 Centimeters",
    },
  },
  {
    material_composition: "80% Cotton, 20% Polyester",
    pattern: "Abstract",
    fit_type: "Relaxed Fit",
    sleeve_type: "Short Sleeve",
    collar_style: "Crew Neck",
    length: "Short Length",
    country_of_origin: "France",
    wash_care: "Machine Wash",
    occasion: "Casual",
    about_this_item: [
      "Soft and comfortable Cotton-Polyester blend fabric",
      "Abstract Print T-shirt for men",
      "Relaxed Fit for casual wear",
      "Perfect for weekend outings",
      "Size chart - S-38, M-40, L-42, XL-44, XXL-46",
    ],
    additional_information: {
      manufacturer: "Abstract Prints Ltd., Paris, France",
      packer: "Abstract Prints Ltd., Paris, France",
      item_weight: "490 g",
      item_dimensions: "24 x 20 x 4 Centimeters",
    },
  },
];

const productTypes = [
  "men",
  "men",
  "men",
  "men",
  "women",
  "women",
  "women",
  "women",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "men",
  "women",
  "women",
  "women",
  "women",
  "women",
  "women",
  "women",
  "women",
];

const imagePaths = [
  "https://ucarecdn.com/b6516ac4-1af9-449b-9cb1-24c0ca643551/mock1.jpg",
  "https://ucarecdn.com/66f08559-c108-4f08-aa9e-7b19a6fa2469/mock2.jpg",
  "https://ucarecdn.com/3cd1e261-c7ba-4859-9399-16f85415402d/mock3.jpg",
  "https://ucarecdn.com/a00e9b56-3fdc-4bda-8432-8044682f54c1/mock4.jpg",
  "https://ucarecdn.com/0aad72a0-2271-49e8-b2f5-5d48abd25435/mock5.jpg",
  "https://ucarecdn.com/613a2614-91ff-4e0f-b4ba-fac565a83536/mock6.jpg",
  "https://ucarecdn.com/6bdd8859-cef8-4128-a6db-c9edbb5fb246/mock7.jpg",
  "https://ucarecdn.com/575b214b-6853-4057-a1e0-0f870fafbe23/mock8.jpg",
  "https://ucarecdn.com/2765c3d6-9d15-489d-bb66-099892af03f4/trendingMock1.jpg",
  "https://ucarecdn.com/b6b3e087-b50b-4245-8b4a-3856e10e3781/trendingMock2.jpg",
  "https://ucarecdn.com/eb907798-91d3-4a27-af59-86c31cc4d415/trendingMock3.jpg",
  "https://ucarecdn.com/a87e0d88-3a16-481c-a53d-1a7c9951d2eb/trendingMock4.jpg",
  "https://ucarecdn.com/7ddabfc0-b6f5-425b-a1ba-0f47d46e519d/trendingMock5.jpg",
  "https://ucarecdn.com/c581db88-8fe4-4ed4-aae8-62209a01a307/trendingMock6.jpg",
  "https://ucarecdn.com/946f6a71-0ef5-4871-a7b2-40eca0ae5a67/trendingMock7.jpg",
  "https://ucarecdn.com/60ad2ef5-304a-4e59-aac8-e92aa0f9b8a3/trendingMock8.jpg",
  "https://ucarecdn.com/2765c3d6-9d15-489d-bb66-099892af03f4/trendingMock1.jpg",
  "https://ucarecdn.com/b6b3e087-b50b-4245-8b4a-3856e10e3781/trendingMock2.jpg",
  "https://ucarecdn.com/eb907798-91d3-4a27-af59-86c31cc4d415/trendingMock3.jpg",
  "https://ucarecdn.com/a87e0d88-3a16-481c-a53d-1a7c9951d2eb/trendingMock4.jpg",
  "https://ucarecdn.com/7ddabfc0-b6f5-425b-a1ba-0f47d46e519d/trendingMock5.jpg",
  "https://ucarecdn.com/c581db88-8fe4-4ed4-aae8-62209a01a307/trendingMock6.jpg",
  "https://ucarecdn.com/946f6a71-0ef5-4871-a7b2-40eca0ae5a67/trendingMock7.jpg",
  "https://ucarecdn.com/60ad2ef5-304a-4e59-aac8-e92aa0f9b8a3/trendingMock8.jpg",
  "https://ucarecdn.com/194f1ca3-ae3b-42fd-ae94-a7b757cdab09/women1.jpg",
  "https://ucarecdn.com/fe5ebba6-090d-4971-a7bd-d055416bdcfd/women2.jpg",
  "https://ucarecdn.com/f9381140-c03e-47b9-84eb-af3caa4fe50f/women3.jpg",
  "https://ucarecdn.com/c5993f8d-0857-49fc-910f-464aa33b6497/women4.jpg",
  "https://ucarecdn.com/92992fff-b07b-492e-90e4-1fb695503129/women5.jpg",
  "https://ucarecdn.com/d8ac491b-8a8d-4ea5-bac1-8bd4c70af719/women6.jpg",
  "https://ucarecdn.com/931eb642-52a4-455f-ade3-41d9e9d95499/women7.jpg",
  "https://ucarecdn.com/5a1103a3-e1e7-4301-9417-decec75b6974/women8.jpg",
];

const originalPrices = [
  1800, 2000, 3000, 3300, 4500, 5250, 6750, 5400, 2700, 2850, 3000, 3300, 1500,
  1650, 1350, 1800, 2700, 2850, 3000, 3300, 1500, 1650, 1350, 1800, 4500, 5250,
  6750, 5400, 4500, 5250, 6750, 5400,
];

const isNewArrivals = [
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];

const isTrendings = [
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
  false,
];

const getRandomDecimal = (min, max) => Math.random() * (max - min) + min;

const generateRandomNumber = () => {
  const baseNumber = Math.floor(Math.random() * (10000 - 100 + 1)) + 100;
  const variation = Math.floor(Math.random() * 21) - 10; // Random value between -10 and 10
  return baseNumber + variation;
};

const generateArray = () => {
  const array = [];
  for (let i = 0; i < 32; i++) {
    array.push(parseFloat(getRandomDecimal(1, 5).toFixed(1)));
  }
  return array;
};

const generateDiscountedPrice = (originalPrice) => {
  const minDiscount = 0.5;
  const maxDiscount = 0.8;
  const discountFactor =
    Math.random() * (maxDiscount - minDiscount) + minDiscount;
  return Math.round(originalPrice * (1 - discountFactor));
};

const productRating = generateArray();

const productRatingCount = Array.from({ length: 32 }, () =>
  generateRandomNumber()
);

const prices = originalPrices.map((price) => generateDiscountedPrice(price));

const products = [];
for (let i = 0; i < productNames.length; i++) {
  const product = {
    product_name: productNames[i],
    product_type: productTypes[i],
    product_description: productDescriptions[i],
    rating: productRating[i],
    rating_count: productRatingCount[i],
    original_price: originalPrices[i],
    price: prices[i],
    image_path: imagePaths[i],
    isNewArrival: isNewArrivals[i],
    isTrending: isTrendings[i],
  };
  products.push(product);
}

mongoose.connect(process.env.MONGO_URL).then(async () => {
  console.log("Connected to Database for Seeding");
  try {
    await Product.insertMany(products);
    console.log("Database Seeding Complete!");
  } catch (error) {
    console.log("An Error occured while seeding: ", error);
  } finally {
    await mongoose.disconnect();
    console.log("Database connection closed");
    process.exit(0);
  }
});
